---
title: "CV"
---

<a href="files/helder_cv_20211216.pdf" class="download" title="Download CV as PDF">Download CV</a>			


### General Information

- **Full Name**: Helder C. R. de Oliveira</td>
- **Nationality**: Brazilian
- **Languages**: Portuguese (native), English, and Italian (beginner)
- **Contact**: [heldercro[AT]gmail[DOT]com](mailto:heldercro[AT]gmail[DOT]com)


### Research Areas

- Medical imaging with a focus on machine learning, computer vision and pattern recognition.


### Education

- **Ph.D. in Electrical Engineering** (2016-2019), [University of São Paulo (USP)](http://www.sel.eesc.usp.br/), Brazil.
    - **WES Canadian equivalent**: Doctorate degree.
    - Thesis: ["New Approaches for Automatic Detection of Architectural Distortion in Digital Mammography and Digital Breast Tomosynthesis"](https://doi.org/10.11606/T.18.2019.tde-02102019-140208).
    - Sandwich period at the **University of Rome - Tor Vergata**, Italy, under supervision of professor [Arianna Mencattini](https://scholar.google.com/citations?hl=en&user=2qegFbUAAAAJ) and funded by Erasmus Mundus program, from Dec/2016 to Jun/2017.

- **M.Sc. in Electrical Engineering** (2014-2015), [University of São Paulo (USP)](http://www.sel.eesc.usp.br/), Brazil.
    - **WES Canadian equivalent**: Master’s degree.
    - Thesis: ["Proposal of Radiation Dose Reduction in Digital Mammography Using New Algorithms for Poisson Noise Filtering"](http://doi.org/10.11606/D.18.2016.tde-29032016-160603)
    
- **B.S. in Computer Science** (2009-2013), [São Paulo State University (UNESP)](http://www.fct.unesp.br), Brazil.
    - **WES Canadian equivalent**: Bachelor's degree - four years.
    - Thesis: "Desenvolvimento de um Framework para o Reconhecimento Óptico de Caracteres". (PDF) [(Slides)](https://speakerdeck.com/helderc/desenvolvimento-de-um-framework-para-o-reconhecimento-ptico-de-caracteres) [(Source Code)](https://github.com/helderc/hIP).
    
    
### Work Experience

- 2022-ongoing, [Southern Alberta Institute of Technology (SAIT)](https://sait.ca):
    - Subject Matter Expert (SME): Operating Systems; Algorithms.
    – Instructor in the [Software Development Diploma](https://www.sait.ca/programs-and-courses/diplomas/software-development):
        - 2023, Spring/Summer:
            - CMPS 369 Operating Systems for Software Development
            - CPSY 200 Software Analysis and Design
            - CMPS 303 Object-Oriented Software Analysis and Design
            - CPRG 311 Advanced Object-Oriented Programming in Java        
        - 2023, Winter: 
            - CMPS 369 Operating Systems for Software Development
            - CPRG 211 Object-Oriented Programming 2 (C#)
            - CPSY 200 Software Analysis and Design
        - 2022, Fall:
            - CMPS 303 Object-Oriented Software Analysis and Design
            - CPRG 311 Advanced Object-Oriented Programming in Java

- 2019-2022: [University of Calgary](https://ucalgary.ca), Canada – Postdoctoral Fellow. Dept. of Electrical and Software Engineering. [Biometric Technologies Laboratory](https://www.ucalgary.ca/btlab/).
    - Research with biometrics and healthcare data using probabilistic graphical models such as, **Bayesian networks** and **Structural Equation Modeling**.
    - **Co-instructor** for two terms (Winter 2020 and 2021) in the course **"ENCM 509 - Fundamentals of Biometric Systems Design"**
    

### Software Development Skills

- **Programming Languages**:Python, MATLAB, R, C, C++, C#, Java...
- **Libraries**: Jupyter Notebook, Numpy, Scipy, Matplotlib, StatsModels, Scikit-Learn, Scikit-Image, Seaborn, TensorFlow, Keras, PyAgrum, Semopy, PyWavelets...


### Services

#### Journals

- Editor:
    - [Springer Trans. on Computational Science (TCSC)](https://www.springer.com/gp/computer-science/lncs/lncs-transactions/computational-science/731224)
    
- Reviewer:
    - [Int'l Journal of Medical Informatics](https://www.journals.elsevier.com/international-journal-of-medical-informatics): 1x2018, 2x2019.
    - [Scientific Reports](https://www.nature.com/srep/): 1x2020, 2x2021, 1x2022.
    - [Computers in Biology and Medicine (CIBM)](https://www.journals.elsevier.com/computers-in-biology-and-medicine/): 1x2020, 8x2022, 2x2023.
    - [IEEE Access](https://ieeeaccess.ieee.org/): 1x2020, 1x2021.
    - [IEEE Computational Intelligence Magazine (CIM)](https://cis.ieee.org/publications/ci-magazine): 1x2021.
    - [IEEE Trans. on Instrumentation and Measurement (TIM)](https://ieee-ims.org/publication/ieee-transactions-instrumentation-measurement): 4x2022, 1x2023.
    - [IEEE Journal of Biomedical and Health Informatics (JBHI)](https://www.embs.org/jbhi/): 1x2022.
    - [MDPI Biosensors](https://www.mdpi.com/journal/biosensors): 2x2021.
    - [MDPI Biomolecules](https://www.mdpi.com/journal/biomolecules): 1x2021.
    - [MDPI Big Data and Cognitive Computing](https://www.mdpi.com/journal/BDCC): 2x2021.
    - [MDPI Int'l Journal of Environmental Research and Public Health](https://www.mdpi.com/journal/ijerph): 1x2021.
    - [MDPI Diagnostics](https://www.mdpi.com/journal/diagnostics): 1x2021, 2x2022, 5x2023.
    - [MDPI Sensors](https://www.mdpi.com/journal/sensors): 4x2022.
    - [MDPI Journal of Imaging](https://www.mdpi.com/journal/jimaging): 2x2022.
    - [MDPI Cancers](https://www.mdpi.com/journal/cancers): 2x2022.
    - [MDPI Tomography](https://www.mdpi.com/journal/tomography): 1x2022.
    - [MDPI Applied Sciences](https://www.mdpi.com/journal/applsci): 1x2022, 1x2023.
    - [MDPI Healthcare](https://www.mdpi.com/journal/healthcare): 1x2022.
    - [Journal of Electronic Imaging (JEI)](https://www.spiedigitallibrary.org/journals/journal-of-electronic-imaging): 1x2021, 1x2023.
    - [Physics in Medicine & Biology](https://iopscience.iop.org/journal/0031-9155): 1x2021.
    - [Springer Trans. on Computational Science (TCSC)](https://www.springer.com/gp/computer-science/lncs/lncs-transactions/computational-science/731224): 4x2022.
    - [MDPI Biomedicines](https://www.mdpi.com/journal/biomedicines): 1x2022.
    - [MDPI Mathematics](https://www.mdpi.com/journal/mathematics): 1x2023.
    - [Revista RESI](http://revistaresi.com.br/) (pt_BR): 1x2021, 1x2023.
    
    
#### Conferences

- Reviewer:
    - Int'l Conf. on Advances in Human-oriented and Personalized Mechanisms, Technologies, and Services (CENTRIC): 2022.
    - IEEE World Congress on Computational Intelligence (IEEE WCCI): 2022.
    - IEEE Int'l Conf. on Autonomous Systems (IEEE ICAS): 2021.
    - IEEE Symp. Series on Computational Intelligence (IEEE SSCI): 2020, 2021, 2022.
    - IEEE Int'l Conf. on Systems, Man, and Cybernetics (IEEE SMC): 2020.

    
### Other Interests

- **Hobbies**:Philately (the art of collecting stamps) and Malware collection.
